# Generated by Django 3.2.4 on 2021-07-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_edit_author', 'Create, edit or delete author'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_book', 'Create, edit or delete book'),)},
        ),
    ]
